services:
  orion-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orion-worker
    command: [celery, "-A", "celery_worker.celery_app", "worker", "--loglevel=info", "-Q", "orion"]
    env_file:
      - path: .env
        required: false
    environment:
      # override paths from env, use paths volumes are mounted to inside the container
      - ORION_STORAGE=/ORION_storage
      - ORION_GRAPHS=/ORION_graphs
      - ORION_LOGS=/ORION_logs
      - SHARED_SOURCE_DATA_PATH=/tmp/shared_data
      # specific to celery
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/ORION
      - "${ORION_STORAGE}:/ORION_storage"
      - "${ORION_GRAPHS}:/ORION_graphs"
      - "${ORION_LOGS}:/ORION_logs"
      - "${SHARED_SOURCE_DATA_PATH}:/tmp/shared_data"
    user: 1000:7474
    networks:
      - app-network

networks:
  app-network:
    external: true
