services:
  mysql:
    image: mysql:latest
    container_name: mysql-pharos
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${PHAROS_DB_PASSWORD}
      MYSQL_DATABASE: ${PHAROS_DB_NAME}
      MYSQL_USER: ${PHAROS_DB_USER}
      MYSQL_PASSWORD: ${PHAROS_DB_PASSWORD}