services:
  orion:
    build:
      context: .
    command: [orion-build, all]
    env_file:
      - path: .env
        required: false
    environment:
      # override paths from env, use paths volumes are mounted to inside the container
      - ORION_STORAGE=/ORION_storage
      - ORION_GRAPHS=/ORION_graphs
    volumes:
      - .:/ORION
      - "${ORION_STORAGE}:/ORION_storage"
      - "${ORION_GRAPHS}:/ORION_graphs"
    user: 7474:7474
