apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orion.fullname" . }}-app-config
  labels:
    {{- include "orion.labels" . | nindent 4 }}
data:
  env-file: |-
    BAGEL_SERVICE_USERNAME={{ .Values.orion.bagel.username }}
    BAGEL_SERVICE_PASSWORD={{ .Values.orion.bagel.password }}
