{{- if not .Values.orion.graphsVolume.use_nfs }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ds-graphs-pvc
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.orion.graphsVolume.size }}
    limits:
      storage: {{ .Values.orion.graphsVolume.size }}
  storageClassName: basic
{{- end }}