{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    app: {{ .Release.Name }}-worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-worker
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-worker
    spec:
      containers:
      - name: worker
        image: "{{ .Values.orion.image.repository }}:{{ .Values.orion.image.tag }}"
        imagePullPolicy: {{ .Values.orion.image.pullPolicy }}
        command: ["celery", "-A", "celery_worker.celery_app", "worker", "--loglevel=info", "-Q", "orion"]
        env:
        - name: CELERY_BROKER_URL
          value: {{ .Values.worker.celery.brokerUrl }}
        - name: CELERY_RESULT_BACKEND
          value: {{ .Values.worker.celery.resultBackend }}
        - name: SHARED_SOURCE_DATA_PATH
          value: {{ .Values.orion.shared_source_data_path }}
        - name: HOME
          value: /ORION
        - name: ORION_STORAGE
          value: /ORION_storage
        - name: ORION_GRAPHS
          value: /ORION_graphs
        - name: ORION_LOGS
          value: /ORION_logs
        - name: BAGEL_SERVICE_USERNAME
          value: {{ .Values.orion.bagel.username }}
        - name: BAGEL_SERVICE_PASSWORD
          value: {{ .Values.orion.bagel.password }}
        - name: LITCOIN_PRED_MAPPING_URL
          value: {{ .Values.orion.normalization.litcoinPredMappingURL }}
        - name: NODE_NORMALIZATION_ENDPOINT
          value: {{ .Values.orion.normalization.nodeNormEndpoint }}
        - name: EDGE_NORMALIZATION_ENDPOINT
          value: {{ .Values.orion.normalization.edgeNormEndpoint }}
        - name: NAMERES_URL
          value: {{ .Values.orion.normalization.nameResolverEndpoint }}
        - name: SAPBERT_URL
          value: {{ .Values.orion.normalization.sapbertEndpoint }}
        - name: BL_VERSION
          value: {{ .Values.orion.normalization.bl_version }}
        # Add other env vars as needed
        volumeMounts:
          - mountPath: /ORION_storage
            name: ds-sources-volume
          - mountPath: /ORION_logs
            name: ds-sources-volume
          - mountPath: /ORION_graphs
            name: ds-graphs-volume
          - mountPath: /tmp/shared_data
            name: shared-data
          - mountPath: /data
            name: ds-neo4j-scratch-volume
            subPath: neo4j_data
          - mountPath: /logs
            name: ds-neo4j-scratch-volume
            subPath: neo4j_logs
          - mountPath: /ORION/.env
            name: app-config
            subPath: env-file
        resources:
          {{- toYaml .Values.orion.resources | nindent 12 }}
      volumes:
        - name: ds-sources-volume
          persistentVolumeClaim:
            claimName: ds-sources-pvc
        - name: ds-graphs-volume
          persistentVolumeClaim:
            claimName: ds-graphs-pvc
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-data-pvc
        - name: ds-neo4j-scratch-volume
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: basic
                resources:
                  requests:
                    storage: {{ .Values.orion.neo4jScratchVolume.size }}
        - name: app-config
          configMap:
            name: {{ include "orion.fullname" . }}-app-config
            defaultMode: 0777
{{- end }}
