# These values can be used to customize the bitnami postgresql helm chart.
# https://github.com/bitnami/charts/tree/main/bitnami/postgresql

architecture: standalone

auth:
  postgresPassword: insecureRootPassword
  username: example-user
  password: example-pass
  database: "drugcentral"

primary:
  extraVolumeMounts:
    - name: pharos-nfs
      mountPath: /ORION_storage
  extraVolumes:
    - name: pharos-nfs
      nfs:
        server: na-projects.edc.renci.org
        path: /stars/Data_services
  resources:
    limits:
      cpu: .5
      memory: 2Gi
    requests:
      cpu: .25
      memory: 1Gi
  persistence:
    size: 10Gi

# this might work
# networkPolicy:
#   ingressRules:
#     primaryAccessOnlyFrom:
#       namespaceSelector:
#         matchLabels:
#           kubernetes.io/metadata.name: data-services

# image:
#  debug: true