# Default values for ORION.

replicaCount: 1

orion:
  graphID: "all"
  graphSpec: "example-graph-spec.yaml"
  # useLocalGraphSpec true if the graphSpec is a file in the codebase (mainly for testing), false if a remote URL
  useLocalGraphSpec: true
  buildMode: true
  image:
    repository: ghcr.io/robokopu24/orion
    pullPolicy: Always
    tag: latest
  graphsVolume:
    use_nfs: false
    nfs_server:
    nfs_path:
    nfs_mount_subpath:
    size: 32Gi # if use_nfs is set to true size is ignored
  sourcesVolume:
    use_nfs: false
    nfs_server:
    nfs_path:
    nfs_mount_subpath:
    size: 32Gi # if use_nfs is set to true size is ignored
  extraVolume:
    use_extra_volume:
    nfs_server:
    nfs_path:
    nfs_mount_subpath:
  neo4jScratchVolume:
    size: 16Gi # if use_nfs is set to true size is ignored
  resources:
    limits:
      cpu: "1"
      memory: 16Gi
      ephemeral-storage: 2Gi
    requests:
      cpu: "1"
      memory: 16Gi
      ephemeral-storage: 1Gi
  httpsProxy:
    useProxy: false
    proxyURL:
  securityContext:
    runAsUser:
    runAsGroup:
  normalization:
    nodeNormEndpoint:
    edgeNormEndpoint:
  openAI:
    openAIKey:
    openAIOrg:

pharos:
  host:
  port:
  user:
  password:
  db_name:

drugcentral:
  host:
  port:
  user:
  password:
  db_name:

# Worker-specific settings
worker:
  enabled: false  # enable running ORION as a celery worker
  replicaCount: 1
  celery:
    brokerUrl: "redis://redis:6379/0"
    resultBackend: "redis://redis:6379/0"