NAMED_THING = 'NamedThing'
BIOLOGICAL_ENTITY = 'BiologicalEntity'
DISEASE_OR_PHENOTYPIC_FEATURE = 'DiseaseOrPhenotypicFeature'
DISEASE = 'Disease'
PHENOTYPIC_FEATURE = 'PhenotypicFeature'
MOLECULAR_ENTITY = 'MolecularEntity'
CHEMICAL_SUBSTANCE = 'ChemicalSubstance'
DRUG = 'Drug'
METABOLITE = 'Metabolite'
ANATOMICAL_ENTITY = 'AnatomicalEntity'
GENE = 'Gene'
GENE_PRODUCT = 'GeneProduct'
GENE_OR_GENE_PRODUCT = 'GeneOrGeneProduct'
SEQUENCE_VARIANT = 'SequenceVariant'
BIOLOGICAL_PROCESS_OR_ACTIVITY = 'BiologicalProcessOrActivity'
MOLECULAR_ACTIVITY = 'MolecularActivity'
BIOLOGICAL_PROCESS = 'BiologicalProcess'
PATHWAY = 'Pathway'
CELLULAR_COMPONENT = 'CellularComponent'
CELL = 'Cell'
GROSS_ANATOMICAL_STRUCTURE = 'GrossAnatomicalStructure'
GENETIC_CONDITION = 'GeneticCondition'
UNSPECIFIED = 'Unspecified'
GENE_FAMILY = 'GeneFamily'
FOOD = 'Food'

# The root of all biolink_model entities
ROOT_ENTITY = NAMED_THING

node_types = [
    NAMED_THING,
    BIOLOGICAL_ENTITY,
    DISEASE_OR_PHENOTYPIC_FEATURE,
    DISEASE,
    PHENOTYPIC_FEATURE,
    MOLECULAR_ENTITY,
    CHEMICAL_SUBSTANCE,
    DRUG,
    METABOLITE,
    ANATOMICAL_ENTITY,
    GENE,
    SEQUENCE_VARIANT,
    BIOLOGICAL_PROCESS_OR_ACTIVITY,
    MOLECULAR_ACTIVITY,
    BIOLOGICAL_PROCESS,
    PATHWAY,
    CELLULAR_COMPONENT,
    CELL,
    GROSS_ANATOMICAL_STRUCTURE,
    GENETIC_CONDITION,
    UNSPECIFIED,
    GENE_FAMILY,
    FOOD
]
